config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :iocs

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "iocs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/ioc.rb
class Ioc < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/iocs_controller.rb
class IocsController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  before_action :set_ioc, only: %i[ show edit update destroy ]
  def index
    @iocs = Ioc.all
  end

  def show
  end

  def new
    @ioc = Ioc.new
  end

  def create
    @ioc = Ioc.new(ioc_params.merge(source: "public"))
    if @ioc.save
      redirect_to @ioc
    else render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @ioc.update(ioc_params)
      redirect_to @ioc
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @ioc.destroy
    redirects_to iocs_path
  end

  private
  def set_ioc
    @ioc = Ioc.find(params[:id])
  end

  private
  def ioc_params
    params.expect(ioc: [ :ioc_type, :value, :first_seen ])
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_password_path, alert: "Try again later." }

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      @user.sessions.destroy_all
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_path, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path, status: :see_other
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/iocs_helper.rb
module IocsHelper
end

app/views/iocs/_form.html.erb
<%= form_with model: ioc do |form| %>
  <% if form.object.errors.any? %>
    <p class="error"><%= form.object.errors.full_messages.first %></p>
  <% end %>

  <div>
    <%= form.label :type %>
    <%= form.select :ioc_type, [['IP Address', 'ip_address'], ['Domain', 'domain'], ['Hash', 'hash']], prompt: "Select type" %>
  </div>

  <div>
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div>
        <%= form.label :"First Seen" %>
        <%= form.datetime_local_field :first_seen %>
  </div>

  <div>
    <%= form.submit :"Submit" %>
  </div>
<% end %>

app/views/iocs/edit.html.erb
<h1>Edit IOC</h1>

<%= render "form", ioc: @ioc %>

<%= link_to "Cancel", @ioc %>

app/views/iocs/index.html.erb
<h1>Indicators of Compromise</h1>

<%= link_to "Report new IOC", new_ioc_path if authenticated? %>


<section id="iocs" class="ioc-index">
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Type</th>
        <th>Value</th>
        <th>Source</th>
        <th>Last Seen</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @iocs.each do |ioc| %>
      <% cache ioc do %>
        <tr>
          <td><%= ioc.id %></td>
          <td><%= ioc.ioc_type %></td>
          <td><%= ioc.value %></td>
          <td><%= ioc.source %></td>
          <td><%= ioc.last_seen.strftime("%Y-%m-%d %H:%M:%S") %></td>
          <td><%= link_to "View details", ioc_path(ioc) %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</section>

app/views/iocs/new.html.erb
<h1>New IOC</h1>

<%= render "form", ioc: @ioc %>

<%= link_to "Cancel", iocs_path %>

app/views/iocs/show.html.erb
<% cache @ioc do %>
  <h1>IOC <%= @ioc.id %></h1>
<% end %>

<dl class="ioc">
  <dt>IOC Type</dt>
  <dd><%= @ioc.ioc_type %></dd>

  <dt>Value</dt>
  <dd><%= @ioc.value %></dd>

  <dt>Source</dt>
  <dd><%= @ioc.source %></dd>

  <dt>First Seen</dt>
  <dd><%= @ioc.first_seen.strftime("%Y-%m-%d %H:%M:%S") %></dd>

  <dt>Last Seen</dt>
  <dd><%= @ioc.last_seen.strftime("%Y-%m-%d %H:%M:%S") %></dd>
</dl>

<% if authenticated? %>
  <%= link_to "Edit", edit_ioc_path(@ioc) %>
  <%= button_to "Delete", @ioc, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
<% end %>
<%= link_to "Back", iocs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Dark Atlas 2" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Dark Atlas 2">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%= link_to "Home", root_path %>
      <%= button_to "Log out", session_path, method: :delete if authenticated? %>
      <%= link_to "Login", new_session_path unless authenticated? %>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>